import axios, { InternalAxiosRequestConfig } from "axios";
import { store } from "../Redux/Store";
import { userSlice } from "../Redux/UserSlice";

class Interceptor {

    public create(): void {

        // Before each request: 
        axios.interceptors.request.use((httpRequest: InternalAxiosRequestConfig) => {

            // Take token: 
            const token = localStorage.getItem("token");

            // Send in header: 
            if(token) {
                httpRequest.headers.set("Authorization", `Bearer ${token}`);
                // httpRequest.headers.Authorization = "Bearer " + token;
            }
            else{
                console.warn("Warning: Axios' JWT Token was not found in the local storage.");
            }

            // Return:
            return httpRequest;

        });

        // Generated by ChatGPT, to solve JWT token expiration.
        axios.interceptors.response.use(
            response => response,

            error => {

                if (error.response?.status === 401) {

                    localStorage.removeItem("token");

                    store.dispatch(
                        userSlice.actions.logoutUser()
                    );
                }

                return Promise.reject(error);
            }
        );
    }
}

export const interceptor = new Interceptor();
