// Generated by ChatGPT, to make TextFields' Legends behave correctly after resetting a form.

import { Controller, Control, FieldValues, Path } from "react-hook-form";
import { TextField, TextFieldProps } from "@mui/material";

type BetterTextFieldProps<T extends FieldValues> = {
    control: Control<T>;
    name: Path<T>;
    label: string;
    rules?: any;
    type?: string;
} & TextFieldProps;

export function BetterTextField<T extends FieldValues>({ control, name, rules, label, ...props }: BetterTextFieldProps<T>) {
    return (
        <Controller
            name={name}
            control={control}
            rules={rules}
            render={({ field, fieldState }) => (
                <TextField
                    {...field}
                    label={label}
                    error={!!fieldState.error}
                    helperText={fieldState.error?.message}
                    {...props}
                />
            )}
        />
    );
}
