// Generated by ChatGPT, to make TextFields' Legends behave correctly after resetting a form.

import { Controller, Control, FieldValues, Path } from "react-hook-form";
import { TextField, TextFieldProps } from "@mui/material";

type BetterTextFieldProps<T extends FieldValues> = {
  name: Path<T>;
  control: Control<T>;
  label: string;
} & TextFieldProps;

export function BetterTextField<T extends FieldValues>({
  name,
  control,
  label,
  ...props
}: BetterTextFieldProps<T>) {
  return (
    <Controller
      name={name}
      control={control}
      render={({ field }) => (
        <TextField {...field} label={label} {...props} />
      )}
    />
  );
}